import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { I18nProvider } from "./_common/i18n/I18nProvider";
import { TopBar } from "./_common/_components/TopBar";
import { Container } from "./_common/_components/Container";
import { Copyright } from "./_common/_components/Copyright";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * グローバルフォントとテーマシェル、i18n、共通トップバーを束ねるルートレイアウト。
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider>
          <div className="min-h-screen bg-zinc-50 font-sans text-zinc-900 dark:bg-black dark:text-zinc-50">
            <Container className="py-10 sm:py-12" padding="lg" maxWidth="default">
              <TopBar />
              {children}
              <Copyright owner="Taishiro Honda" />
            </Container>
          </div>
        </I18nProvider>
      </body>
    </html>
  );
}
